### ISSUE TITLE
E-mail to registrant: move the disclaimer from bottom to top of the email template

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#92]
The disclaimer currently located at the end should be brought to the beginning to assure receiver is able to read it.

as described here:
https://docs.google.com/document/d/1O5GQqRKExfBwYG25WXkeSVo9JSxjtakRsq7IvAYmjmU/edit?ts=5b17b9c7#heading=h.ds1lvreq0xmh

**Comment by vohmar** [comment]
text in english part of the email differs from the text in the document metioned in description.

@artur-beljajev please review the russion version
current russiona part in the email:

> Уважаемый контакт домена timo-6k2.ee,
> Eesti Interneti SA (EIS) уведомляет Вас о новом сообщении.
> Вы являетесь получателем, т.к. закон о защите данных не позволяет публиковать данные частных лиц. Вместо этого, EIS позволяет связаться с контактами домена через свой сайт.
> EIS не проверяет подлинность сообщения и не устанавливает личность отправителя;
> Вы не обязаны отвечать на данное письмо;
> В случае ответа на сообщение, EIS не является третьей стороной, и вся дальнейшая переписка ведется исключительно между вами и отправителем;
> 
> Отправитель: Timo Võhmar, timo.vohmar@internet.ee
> 
> Сообщение:

**Comment by maciej-szlosarczyk** [comment]
@vohmar This should be fixed now. The issue was caused by the fact that the text in Google Docs was edited after I took it up for development, some time last week. Similarly, the Estonian text was also different now than it was a week ago. We shouldn't do that.

Artur is the person who provided the Russian text, I asked him for it last week.
