### ISSUE TITLE
Separate db instance

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#93]
Before the GDPR update reswhois like whois worked on separate whois db instance - read only db with limited set of registry data necessary for whois service

now with the private registrant contact solution we need write access to the whois db and becaouse of that we cannot use the same instance any more. 

DB replication functionality is used for generating whois db and at least in Postgres v9 it is not possible to use read write db for destination.

To solve this one option would be to use different db instance for writing ie in current registry db copy to suport multiple whois services.

**Comment by maciej-szlosarczyk** [comment]
I am not sure what's the problem here, at least not from development side. This is an operational concern that was not spelled out at any point during the latest development, and the desired solution is not supported by Ruby on Rails. From a pure Rails standpoint, there's no such thing as `read-only` database. If a database is specified in configuration, it is assumed that you have `WRITE` permissions there.

Currently, REST WHOIS does not write to `whois_records` table, it does need write access to separate `contact_requests` table where the information about emails sent to private registrants is stored. Given Postgres' granular permissions, it can effectively run a role that has `SELECT` permissions on `whois_records` and all permissions on `contact_requests`, but it's still our convention, not something we can get out of Rails.

**Comment by teadur** [comment]
Can rails use several db's inside one application ?

**Comment by maciej-szlosarczyk** [comment]
It is not the default behaviour, but it can be done.

**Comment by teadur** [comment]
that would be the simplest solution to just use the email functionality from other db where the app can write.
